/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelos.DetalleNomina;
import Modelos.DetalleNominaDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maico
 */
public class ConsultarDetallesNómina extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultarDetallesNómina.class.getName());
    
    private int idNomina;

    public ConsultarDetallesNómina() {
    initComponents();
        }
    public ConsultarDetallesNómina(int idNomina) {
        initComponents();
        
         this.idNomina = idNomina;
        cargarDetallesNomina(idNomina);
        
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel72 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblDetalleNomina = new javax.swing.JTable();
        jLabel153 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel72.setBackground(new java.awt.Color(204, 255, 255));
        jPanel72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        jPanel72.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDetalleNomina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código Empleado", "Empleado", "Salario", "Bonif.", "Deducciones", "Neto", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(tblDetalleNomina);

        jPanel72.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 810, -1));

        jLabel153.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel153.setText("Detalle de Nómina");
        jPanel72.add(jLabel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jButton31.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jButton31.setText("Exportar PDF");
        jButton31.addActionListener(this::jButton31ActionPerformed);
        jPanel72.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, -1));

        jButton28.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jButton28.setText("Cerrar");
        jButton28.addActionListener(this::jButton28ActionPerformed);
        jPanel72.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        jPanel1.add(jPanel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
      
    DetalleNomina reporte = new DetalleNomina();

    reporte.generarPDF(idNomina);
    }//GEN-LAST:event_jButton31ActionPerformed
    private void cargarDetallesNomina(int idNomina) {

    DetalleNominaDAO dao = new DetalleNominaDAO();

    List<Object[]> datos = dao.obtenerDetallesPorNomina(idNomina);

    DefaultTableModel modelo = (DefaultTableModel) tblDetalleNomina.getModel();

    modelo.setRowCount(0);

    for (Object[] fila : datos) {
        modelo.addRow(fila);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultarDetallesNómina().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton31;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JTable tblDetalleNomina;
    // End of variables declaration//GEN-END:variables
}
