/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Main.Menu;

/**
 *
 * @author maico
 */
public class Login1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login1.class.getName());

    /**
     * Creates new form Login1
     */
    public Login1() {
        setTitle("NOMIPRO");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpLogin2 = new javax.swing.JPanel();
        jblUsuario2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jblContraseña2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jpwClave = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jpLogin2.setBackground(new java.awt.Color(204, 255, 255));
        jpLogin2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jpLogin2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblUsuario2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jblUsuario2.setText("Nombre de Usuario");
        jpLogin2.add(jblUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 127, -1, -1));

        txtUsuario.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsuario.setFocusTraversalPolicyProvider(true);
        txtUsuario.setVerifyInputWhenFocusTarget(false);
        jpLogin2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 152, 185, 30));

        jblContraseña2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jblContraseña2.setText("Contraseña");
        jpLogin2.add(jblContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 194, -1, -1));

        btnRegistrar.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        btnRegistrar.setText("Ingresar");
        btnRegistrar.addChangeListener(this::btnRegistrarStateChanged);
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        jpLogin2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));
        jpLogin2.add(jpwClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo .png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jpLogin2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 160, 130));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jpLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jpLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnRegistrarStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarStateChanged

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblContraseña2;
    private javax.swing.JLabel jblUsuario2;
    private javax.swing.JPanel jpLogin2;
    public javax.swing.JPasswordField jpwClave;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public class btnLogin {

        public btnLogin() {
        }
    }
}
